---
version: 2.1

executors:
  build-executor:
    docker:
      - image: quay.io/labmonkeys/cimg-base:2022.01-20.04.b38

commands:
  make-image:
    description: "Build OCI image and publish from main branch"
    parameters:
      workdir:
        default: "~/project"
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build OCI image and publish from main branch
          command: |
            cd << parameters.workdir >> && pwd
            if git show --name-only --format='' . | grep ""; then
              echo "Changes detected trigger build"
              if [[ "${CIRCLE_BRANCH}" == "main" ]]; then make publish BUILD_VERSION_SUFFIX=".b${CIRCLE_BUILD_NUM}"; else make oci; fi
            else
              echo "No changes in directory << parameters.workdir >> detected, skip build."
            fi

workflows:
  version: 2

  build:
    jobs:
      - antora:
          context: "Publishing"
      - cerebro:
          context: "Publishing"
      - gobgp:
          context: "Publishing"
      - lldpd:
          context: "Publishing"
      - maven-11-jdk:
          context: "Publishing"
      - maven-17-jdk:
          context: "Publishing"
      - net-snmp:
          context: "Publishing"
      - gobetween:
          context: "Publishing"
      - onms-horizon:
          context: "Publishing"
jobs:
  antora:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./antora"

  cerebro:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./cerebro"

  gobgp:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./gobgp"

  lldpd:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./lldpd"

  maven-11-jdk:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./maven-11-jdk"

  maven-17-jdk:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./maven-17-jdk"

  net-snmp:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./net-snmp"

  gobetween:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./gobetween"

  onms-horizon:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./onms-horizon"
