---
version: 2.1

executors:
  build-executor:
    docker:
      - image: quay.io/labmonkeys/cimg-base:20.04-20211130.b33

commands:
  make-image:
    description: "Build OCI image and publish from main branch"
    parameters:
      workdir:
        default: "~/project"
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build OCI image and publish from main branch
          command: |
            cd << parameters.workdir >> && pwd
            if [[ "${CIRCLE_BRANCH}" == "main" ]]; then make publish BUILD_VERSION_SUFFIX=".b${CIRCLE_BUILD_NUM}"; else make oci; fi

workflows:
  version: 2

  build:
    jobs:
      - antora:
          context: "Publishing"
      - gobgp:
          context: "Publishing"
      - lldpd:
          context: "Publishing"
      - net-snmp:
          context: "Publishing"
jobs:
  antora:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./antora"

  gobgp:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./gobgp"

  lldpd:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./lldpd"

  net-snmp:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./net-snmp"
