---
version: 2.1

executors:
  build-executor:
    docker:
      - image: quay.io/labmonkeys/cimg-base:2022.08-22.04.b46

commands:
  make-image:
    description: "Build OCI image and publish from main branch"
    parameters:
      workdir:
        default: "~/project"
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build OCI image and publish from main branch
          command: |
            cd << parameters.workdir >> && pwd
            if git show --name-only --format='' . | grep ""; then
              echo "Changes detected trigger build"
              if [[ "${CIRCLE_BRANCH}" == "main" ]]; then make publish BUILD_VERSION_SUFFIX=".b${CIRCLE_BUILD_NUM}"; else make oci; fi
            else
              echo "No changes in directory << parameters.workdir >> detected, skip build."
            fi

workflows:
  version: 2

  build:
    jobs:
      - antora:
          context: "Publishing"
      - cerebro:
          context: "Publishing"
      - diag:
          context: "Publishing"
      - dupligator:
          context: "Publishing"
      - featmap:
          context: "Publishing"
      - freeradius:
          context: "Publishing"
      - gobetween:
          context: "Publishing"
      - gobgp:
          context: "Publishing"
      - horizon-stream:
          context: "Publishing"
      - karaf:
          context: "Publishing"
      - lldpd:
          context: "Publishing"
      - maven-11-jdk:
          context: "Publishing"
      - maven-17-jdk:
          context: "Publishing"
      - maven-18-jdk:
          context: "Publishing"
      - net-snmp:
          context: "Publishing"
      - onms-horizon:
          context: "Publishing"
      - pleroma:
          context: "Publishing"

jobs:
  antora:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./antora"

  cerebro:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./cerebro"

  diag:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./diag"

  dupligator:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./dupligator"

  featmap:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./featmap"

  freeradius:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./freeradius"

  gobetween:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./gobetween"

  gobgp:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./gobgp"

  horizon-stream:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./horizon-stream"

  karaf:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./karaf"

  lldpd:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./lldpd"

  maven-11-jdk:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./maven-11-jdk"

  maven-17-jdk:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./maven-17-jdk"

  maven-18-jdk:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./maven-18-jdk"

  net-snmp:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./net-snmp"

  onms-horizon:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./onms-horizon"

  pleroma:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./pleroma"
