---
version: '3'
services:
  jira-exporter:
    image: quay.io/labmonkeys/jira-exporter:1.1.0.b1039
    container_name: jira-exporter
    environment:
      JIRA_URL: https://issues.opennms.org
      JIRA_USERNAME: 'indigo'
      JIRA_PASSWORD: 'MjE1NzcyNTE0NDE4OvaDko2Qe81NI/OxsAMWX+aGs8vG'
    command: ['--projects=NMS']
    ports:
      - '9653:9653/tcp'

